//
//  TextContentCardView.swift
//  CocoaHeadsAI
//
//  Created by Dimitri Brukakis on 03.10.25.
//

import SwiftUI

struct TextContentCardView: View {
    let title: String?
    let text: String
    let icon: String?
    let footnote: String?

    init(title: String? = nil, text: String, icon: String? = nil, footnote: String? = nil) {
        self.title = title
        self.text = text
        self.icon = icon
        self.footnote = footnote
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            if let title, !title.isEmpty {
                HStack(spacing: 8) {
                    if let icon, !icon.isEmpty {
                        Image(systemName: icon)
                            .foregroundStyle(.secondary)
                    }
                    Text(title)
                        .font(.headline)
                        .foregroundStyle(.primary)
                    Spacer(minLength: 0)
                }
            }

            Text(text)
                .font(.body)
                .foregroundStyle(.primary)
                .textSelection(.enabled)
                .frame(maxWidth: .infinity, alignment: .leading)

            if let footnote, !footnote.isEmpty {
                Text(footnote)
                    .font(.footnote)
                    .foregroundStyle(.secondary)
                    .padding(.top, 4)
            }
        }
        .padding(16)
        .background(
            .thinMaterial,
            in: RoundedRectangle(cornerRadius: 16, style: .continuous)
        )
    }
}

#Preview {
    ScrollView {
        VStack(spacing: 16) {
            TextContentCardView(title: "Answer", text: "Here is a helpful response to your question. It can span multiple lines and supports text selection.", icon: "sparkles", footnote: "Generated by CocoaHeadsAI")
            TextContentCardView(text: "A simple card without a title or icon.")
        }
        .padding()
    }
}
